rewrite commit-and-push in bash

diff --git a/bin/git-commit-and-push b/bin/git-commit-and-push
--- a/bin/git-commit-and-push
+++ b/bin/git-commit-and-push
@@ -1,14 +1,14 @@
-#!/usr/bin/env python3
+#!/bin/bash
 
-import sys
-import subprocess
+set -e
 
-def main():
-    message = sys.argv[1]
-    subprocess.check_call(["git", "commit", "--all",
-                           "--message", message])
-    subprocess.check_call(["git", "push"])
+function main() {
+  if [[ -z "$1" ]] ; then
+    echo "Missing commit message"
+    return 1
+  fi
+  git commit --all --message "$1"
+  git push
+}
 
-
-if __name__ == "__main__":
-    main()
+main "$@"
